# Generated by Django 3.0.6 on 2020-07-10 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('autor', models.CharField(max_length=100, verbose_name='Автор')),
                ('start', models.DateField(default=datetime.date.today, verbose_name='Начало')),
                ('end', models.DateField(verbose_name='Окончание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('files_dir', models.CharField(max_length=500, verbose_name='Путь к прикрепленным файлам')),
            ],
            options={
                'ordering': ['end', 'title'],
            },
        ),
    ]
