# Generated by Django 3.0.6 on 2020-08-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_auto_20200726_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='files_dir',
        ),
    ]
