# Generated by Django 3.0.6 on 2020-08-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_remove_reading_files_dir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-end', 'title']},
        ),
    ]
