# Generated by Django 3.0.6 on 2020-05-24 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(max_length=4, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoughts.Paragraph')),
            ],
            options={
                'ordering': ['paragraph'],
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created', models.DateField(default=datetime.date.today)),
                ('last_modified', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('finished', models.BooleanField()),
                ('topics', models.ManyToManyField(related_name='thoughts', to='thoughts.Topic')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
