# Generated by Django 3.0.6 on 2020-08-10 12:58

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_auto_20200526_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='created',
            field=models.DateField(default=datetime.date.today, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='text',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Темы'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='topics',
            field=models.ManyToManyField(related_name='thoughts', to='thoughts.Topic', verbose_name='Темы'),
        ),
    ]
