# Generated by Django 3.0.6 on 2020-08-12 06:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_auto_20200810_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='paragraph',
            field=models.IntegerField(choices=[(111, '111 Мышление'), (112, '112 Чувства'), (12, '12 Мировоззрение'), (13, '13 Знания'), (141, '141 Здоровье'), (142, '142 Спорт'), (143, '143 Внешний вид'), (21, '21 Социальные навыки'), (221, '221 Семья'), (222, '222 Родственники и друзья'), (223, '223 Знакомства'), (31, '31 Общий комфорт и удовлетворенность'), (321, '321 Регулярный отдых'), (322, '322 Особые мероприятия и отпуска'), (41, '41 Финансы'), (42, '42 Карьера'), (43, '43 Быт'), (51, '51 Общая эффективность'), (52, '52 Развитие и применение ПИС')], verbose_name='Пункт'),
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
