# Generated by Django 3.0.6 on 2020-06-30 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200423_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='paragraph',
            field=models.IntegerField(choices=[(111, '111 Мышление'), (112, '112 Чувства'), (12, '12 Мировоззрение'), (13, '13 Знания'), (141, '141 Здоровье'), (142, '142 Спорт'), (143, '143 Внешний вид'), (21, '21 Социальные навыки'), (221, '221 Семья'), (222, '222 Родственники и друзья'), (223, '223 Знакомства'), (31, '31 Общий комфорт и удовлетворенность'), (321, '321 Регулярный отдых'), (322, '322 Особые мероприятия и отпуска'), (41, '41 Финансы'), (42, '42 Карьера'), (43, '43 Быт'), (51, '51 Общая эффективность'), (52, '52 Развитие и применение ПИС')], verbose_name='Пункт'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'В работе'), (1, 'Выполнено'), (2, 'Провалено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Заголовок'),
        ),
    ]
