# Generated by Django 3.0.6 on 2020-08-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200630_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-end', 'title']},
        ),
    ]
