# Generated by Django 3.0.3 on 2020-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200423_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayreport',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
