# Generated by Django 3.0.3 on 2020-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200423_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeobject',
            name='object_type',
        ),
        migrations.AddField(
            model_name='dayreportrow',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='financeobject',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financeobject',
            name='need_description',
            field=models.BooleanField(default=False),
        ),
    ]
