# Generated by Django 3.0.6 on 2020-06-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20200618_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrow',
            name='fin_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.FinanceObject'),
        ),
        migrations.AlterField(
            model_name='dayreportrow',
            name='fin_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='finance.FinanceObject'),
        ),
    ]
