# Generated by Django 3.0.6 on 2020-06-21 08:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20200618_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.IntegerField(choices=[(0, 'Week'), (1, 'Month'), (2, 'Quarter')], verbose_name='Тип отчета')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('p1', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='П1')),
                ('p13', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='П13')),
                ('p3', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='П3')),
                ('p_union', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Общая оценка')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'ordering': ('date',),
                'get_latest_by': 'date',
            },
        ),
        migrations.AddConstraint(
            model_name='periodicreports',
            constraint=models.UniqueConstraint(fields=('report_type', 'date'), name='unique report type'),
        ),
    ]
