# Generated by Django 3.0.6 on 2020-06-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20200621_0845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeriodicReports',
            new_name='PeriodicReport',
        ),
    ]
