# Generated by Django 3.0.6 on 2020-06-24 11:25

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20200622_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayreportrow',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 11, 25, 5, 211981, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayreport',
            name='p13',
            field=models.PositiveIntegerField(verbose_name='П13'),
        ),
        migrations.AlterField(
            model_name='periodicreport',
            name='p1',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10.0)], verbose_name='П1'),
        ),
        migrations.AlterField(
            model_name='periodicreport',
            name='p13',
            field=models.FloatField(verbose_name='П13'),
        ),
        migrations.AlterField(
            model_name='periodicreport',
            name='p3',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10.0)], verbose_name='П3'),
        ),
        migrations.AlterField(
            model_name='periodicreport',
            name='p_union',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10.0)], verbose_name='Общая оценка'),
        ),
    ]
