# Generated by Django 3.0.6 on 2020-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20200624_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayreportrow',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
