# Generated by Django 3.0.6 on 2020-06-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20200624_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicreport',
            name='report_type',
            field=models.IntegerField(choices=[(0, 'Недельный'), (1, 'Месячный'), (2, 'Квартальный')], verbose_name='Тип отчета'),
        ),
    ]
