# Generated by Django 3.0.6 on 2020-06-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_budgetrow_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeobject',
            options={'ordering': ('-is_positive', 'title')},
        ),
    ]
