# Generated by Django 3.0.6 on 2020-07-04 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20200701_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.date.today, unique=True, verbose_name='Месяц')),
                ('incomes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('outcomes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'ordering': ('month',),
            },
        ),
    ]
