# Generated by Django 3.0.6 on 2020-07-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_financeregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeregister',
            name='incomes',
        ),
        migrations.RemoveField(
            model_name='financeregister',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='financeregister',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
