# Generated by Django 3.0.6 on 2020-07-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20200705_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetrow',
            old_name='budget',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='dayreportrow',
            old_name='report',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='dayreportrow',
            name='description',
        ),
        migrations.AddField(
            model_name='budget',
            name='rows_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dayreport',
            name='rows_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dayreport',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dayreport',
            name='total_outcome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='budgetrow',
            name='fin_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_rows', to='finance.FinanceObject'),
        ),
        migrations.AlterField(
            model_name='dayreportrow',
            name='fin_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_rows', to='finance.FinanceObject'),
        ),
    ]
