# Generated by Django 3.0.6 on 2020-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20200706_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeregister',
            options={'get_latest_by': 'month', 'ordering': ('month',)},
        ),
        migrations.AlterField(
            model_name='periodicreport',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Итог ДС'),
        ),
    ]
