# Generated by Django 3.0.6 on 2020-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_auto_20200710_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrow',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dayreport',
            name='train',
            field=models.BooleanField(default=False, verbose_name='Тренировка'),
        ),
        migrations.AddField(
            model_name='dayreportrow',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financeobject',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архиваная'),
        ),
        migrations.AddField(
            model_name='periodicreport',
            name='trains',
            field=models.PositiveIntegerField(default=0, verbose_name='Тренировок'),
        ),
    ]
