# Generated by Django 3.0.6 on 2020-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_auto_20200726_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrow',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dayreportrow',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
