# Generated by Django 3.0.6 on 2020-08-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20200726_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='dayreport',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='periodicreport',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='periodicreport',
            old_name='trains',
            new_name='train',
        ),
    ]
