# Generated by Django 3.0.6 on 2020-08-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20200803_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicreport',
            old_name='train',
            new_name='trains',
        ),
    ]
