# Generated by Django 3.0.6 on 2020-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_auto_20200809_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeobject',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архивная'),
        ),
    ]
