# Generated by Django 3.0.6 on 2020-08-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20200810_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetrow',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='dayreportrow',
            options={'ordering': ('-date',)},
        ),
    ]
